---
- name: WaddlePerf Client
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - vars/base.yml
  tasks:
    - name: Build
      tags:
        - build
      block:
        - name: Execute build tasks
          ansible.builtin.include_tasks:
            file: "{{ job.file }}"
            apply:
              tags:
                - build
          loop:
            - { file: "jobs/build/user.yml" }
            - { file: "jobs/build/packages.yml" }
            - { file: "jobs/build/iperf3.yml" }
            - { file: "jobs/build/filesystem.yml" }
            - { file: "jobs/build/security.yml" }
            - { file: "jobs/build/mtr.yml", when: "mtr.enabled" }
            - { file: "jobs/build/pping.yml", when: "pping.enabled" }
            - { file: "jobs/build/httptrace.yml", when: "httptrace.enabled" }
            - { file: "jobs/build/sshping.yml", when: "sshping.enabled" }
          loop_control:
            loop_var: job

    - name: Run
      tags:
        - run
        - hash
      block:
        - name: Execute run tasks
          ansible.builtin.include_tasks:
            file: "{{ job.file }}"
            apply:
              tags:
                - run
          loop:
            - { file: "jobs/run/client.yml" }
            - { file: "jobs/run/s3.yml", tags: ["run", "s3"] }
          loop_control:
            loop_var: job

    - name: Health Checks
      tags:
        - run
        - health
        - test
      when: ansible_os_family == "Debian"
      block:
        - name: Static Health Checks
          tags: static
          ansible.builtin.include_tasks:
            file: jobs/tests/{{ job }}.yml
            apply:
              tags:
                - run
                - health
                - test
                - static
          loop:
            - files
          loop_control:
            loop_var: job