---
- name: WaddlePerf
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - name: Build
      tags:
        - build
      block:
        - name: Install User
          ansible.builtin.include_tasks:
            file: "jobs//build/user.yml"
            apply:
              tags:
                - build   
        - name: Create iperf3 binary
          ansible.builtin.include_tasks:
            file: jobs/build/packages.yml
            apply:
              tags:
                - build
        - name: Create iperf3 binary
          ansible.builtin.include_tasks:
            file: jobs/build/iperf3.yml
            apply:
              tags:
                - build
        - name: Create filesystem directories and structure
          ansible.builtin.include_tasks:
            file: jobs/build/filesystem.yml
            apply:
              tags:
                - build
        - name: Create logs and sudoers
          ansible.builtin.include_tasks:
            file: jobs/build/security.yml
            apply:
              tags:
                - build
        - name: Create built in certificate
          ansible.builtin.include_tasks:
            file: jobs/build/certificate.yml
            apply:
              tags:
                - build
        - name: Create MTR testing
          when: mtr.enabled
          ansible.builtin.include_tasks:
            file: "jobs/build/mtr.yml"
            apply:
              tags:
                - build
        - name: Create PPING testing
          when: pping.enabled
          ansible.builtin.include_tasks:
            file: "jobs/build/pping.yml"
            apply:
              tags:
                - build
        - name: Create HttpTraceroute testing
          when: httptrace.enabled
          ansible.builtin.include_tasks:
            file: "jobs/build/httptrace.yml"
            apply:
              tags:
                - build    
       # - name: Create cron jobs
       #   ansible.builtin.include_tasks:
       #     file: "jobs/build/cron.yml"
       #     apply:
       #       tags:
       #         - build        
        - name: Install NGINX
          ansible.builtin.include_tasks:
            file: "jobs/build/nginx.yml"
            apply:
              tags:
                - build     
        - name: Install SSHPing
          when: sshping.enabled
          ansible.builtin.include_tasks:
            file: "jobs/build/sshping.yml"
            apply:
              tags:
                - build          
    - name: Run
      tags:
        - run
        - hash
      block:
        - name: Configure NGINX default site
          ansible.builtin.include_tasks:
            file: jobs/run/nginx.yml
            apply:
              tags:
                - run
          when: iperf.server.enabled == "1"
        - name: Run in server mode
          ansible.builtin.include_tasks:
            file: jobs/run/server.yml
            apply:
              tags:
                - run
          when: iperf.server.enabled == "1"
        - name: create user hash file
          ansible.builtin.include_tasks:
            file: jobs/run/hash.yml
            apply:
              tags:
                - run
                - hash
        - name: Create client run script
          ansible.builtin.include_tasks:
            file: jobs/run/client.yml
            apply:
              tags:
                - run
        - name: Run S3 Uploader
          ansible.builtin.include_tasks:
            file: jobs/run/s3.yml
            apply:
              tags:
                - run
                - s3
        - name: Test Files
          ansible.builtin.include_tasks:
            file: jobs/tests/files.yml
            apply:
              tags:
                - run
                - test
          loop:
            - "{{ iperf.userfile }}"
            - "/var/www/{{ app.title }}/results.log"
            - "/var/www/{{ app.title }}/public.pem"
    - name: Health Checks
      tags:
        - run
        - health
        - test
      ansible.builtin.include_tasks:
        file: jobs/tests/{{ item }}.yml
        apply:
          tags:
            - run
            - health
            - test
      loop:
        - nginx
        - host
