---
- name: WaddlePerf3
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - name: Build
      tags:
        - build
      block:
        - name: Create iperf3 binary
          include_tasks:
            file: jobs/build/install-packages.yml
            apply:
              tags:
                - build
        - name: Create iperf3 binary
          include_tasks:
            file: jobs/build/build-iperf3.yml
            apply:
              tags:
                - build
        - name: Create filesystem directories and structure
          include_tasks:
            file: jobs/build/build-filesystem.yml
            apply:
              tags:
                - build
        - name: Create logs and sudoers
          include_tasks:
            file: jobs/build/build-security.yml
            apply:
              tags:
                - build
        - name: Create built in certificate
          include_tasks:
            file: jobs/build/build-certificate.yml
            apply:
              tags:
                - build
        - name: Get HTTP Ping installed
          include_tasks:
            file: jobs/build/build-http-ping.yml
            apply:
              tags:
                - build
        - name: Set NGINX permissions
          include_tasks:
            file: jobs/build/set-nginx-permissions.yml
            apply:
              tags:
                - build
    - name: Run
      tags:
        - run
        - hash
      block:
        - name: Run in server mode
          include_tasks:
            file: jobs/run/server.yml
            apply:
              tags:
                - run
          when: iperf.server.enable == "1"
        - name: create user hash file
          include_tasks:
            file: jobs/run/hash.yml
            apply:
              tags:
                - run
                - hash
        - name: Create client run script
          include_tasks:
            file: jobs/run/client.yml
            apply:
              tags:
                - run
        - name: Test Files
          include_tasks:
            file: jobs/tests/test-files.yml
            apply:
              tags:
                - run
                - test
          loop:
            - "{{ iperf.userfile }}"
            - "/var/www/{{ app.title }}/results.log"
            - "/var/www/{{ app.title }}/public.pem"
