---
client:
  thin: true
server:
  hosts: 
    - 127.0.0.1
Protocols:
  SSH: true
  HTTP: true
  DNS: true
  TCP: true
  ICMP: true
  speedtest: true
ssh:
  port: 22
  user: root
  password: password
  key: /root/.ssh/id_rsa
  key_password: password
  timeout: 10
  retries: 3
  keepalive: 60
http:
  port: 80
  timeout: 10
  retries: 3
  url: http://localhost.internal
iperf3:
  protocol: TCP
  port: 5201
  timeout: 10
  retries: 3
  keepalive: 60
  size: 1M
