run:
  user: ptg-user
  autoupdates: true # TODO move to DOCKERFILE
app:
  title: "waddleperf"
build:
  threads: "{{ lookup('env', 'BUILD_THREADS') }}"
iperf:
  authentication: "{{ lookup('env', 'IPERF_AUTHENTICATION') }}"
  url: "{{ lookup('env', 'IPERF_URL') }}"
  client:
    enabled: true # TODO move to DOCKERFILE
    streams: "{{ lookup('env', 'IPERF_CLIENT_STREAMS') }}"
    bitrate: "{{ lookup('env', 'IPERF_CLIENT_BITRATE') }}"
    return: "{{ lookup('env', 'IPERF_CLIENT_RETURN') }}"
    logfile: "{{ lookup('env', 'IPERF_CLIENT_LOGFILE') }}"
  server:
    enabled: "{{ lookup('env', 'IPERF_SERVER_ENABLE') }}"
    ip: "{{ lookup('env', 'IPERF_SERVER_IP') }}"
    port: "{{ lookup('env', 'IPERF_SERVER_PORT') }}"
  format: json
  userfile: "/opt/{{ app.title }}/users.csv"
  protocol: "{{ lookup('env', 'IPERF_PROTOCOL') }}"
  username: "{{ lookup('env', 'IPERF_USERNAME') }}"
  password: "{{ lookup('env', 'IPERF_PASSWORD') }}"
web:
  port: "{{ lookup('env', 'WEB_PORT') }}"
  sport: "{{ lookup('env', 'WEB_SPORT') }}" 
  host: "{{ lookup('env', 'WEB_HOST') }}"
mtr:
  version: 0.95 #TODO move to DOCKERFILE
  enabled: true #TODO move to DOCKERFILE
  compile: false #TODO move to DOCKERFILE
  use6: false #TODO move to DOCKERFILE # If true, use ipv6 only
  use4: false #TODO move to DOCKERFILE # If true, use ipv4 only
  localport: 4343
  destport: 9090
  desthost: localhost
  packet:
    size: 1450 #TODO move to DOCKERFILE
    count: 2
    interval: 5
    protocl: icmp # icmp, udp, tcp
    tos: 0000
  lookups:
    domains: false
    ipinfo: false
    asninfo: false 
pping:
  version: 0.8.3 #TODO move to DOCKERFILE
  enabled: true #TODO move to DOCKERFILE
  protocol: http # http, dns, tls, quic
  count: 2
  interval: 2
  use4: false
  use6: false
  destport: 9090
  desthost: localhost
  
httptrace:
  enabled: true #TODO move to DOCKERFILE
s3:
  interval: 10
  enabled: false #TODO move to DOCKERFILE
  url: localhost #TODO move to DOCKERFILE
  bucket: waddleperf #TODO move to DOCKERFILE
  encrypt: false #TODO move to DOCKERFILE
  compatibility: true #TODO move to DOCKERFILE
  key:
    access: change #TODO move to DOCKERFILE
    secret: menow #TODO move to DOCKERFILE
results:
  - output.json 
healthcheck:
  enabled: true #TODO move to DOCKERFILE
  interval: 10 #TODO move to DOCKERFILE
autoperf:
  enabled: false #TODO move to DOCKERFILE
  interval: 10 #TODO move to DOCKERFILE