run:
  user: ptg-user
app:
  title: "waddleperf3"
build:
  threads: "{{ lookup('env', 'BUILD_THREADS') }}"
iperf:
  url: "{{ lookup('env', 'IPERF_URL') }}"
  client:
    streams: "{{ lookup('env', 'IPERF_CLIENT_STREAMS') }}"
  server:
    enable: "{{ lookup('env', 'IPERF_SERVER_ENABLE') }}"
    ip: "{{ lookup('env', 'IPERF_SERVER_IP') }}"
    port: "{{ lookup('env', 'IPERF_SERVER_PORT') }}"
  format: "{{ lookup('env', 'IPERF_FORMAT') }}"
  userfile: "/opt/{{ app.title }}/users.csv"
  protocol: "{{ lookup('env', 'IPERF_PROTOCOL') }}"
  username: "{{ lookup('env', 'IPERF_USERNAME') }}"
  password: "{{ lookup('env', 'IPERF_PASSWORD') }}"
web:
  port: "{{ lookup('env', 'WEB_PORT') }}"
