run:
  user: ptg-user
app:
  title: "waddleperf3"
build:
  threads: "{{ lookup('env', 'BUILD_THREADS') }}"
iperf:
  authentication: "{{ lookup('env', 'IPERF_AUTHENTICATION') }}"
  url: "{{ lookup('env', 'IPERF_URL') }}"
  client:
    streams: "{{ lookup('env', 'IPERF_CLIENT_STREAMS') }}"
    bitrate: "{{ lookup('env', 'IPERF_CLIENT_BITRATE') }}"
    return: "{{ lookup('env', 'IPERF_CLIENT_RETURN') }}"
    logfile: "{{ lookup('env', 'IPERF_CLIENT_LOGFILE') }}"
  server:
    enable: "{{ lookup('env', 'IPERF_SERVER_ENABLE') }}"
    ip: "{{ lookup('env', 'IPERF_SERVER_IP') }}"
    port: "{{ lookup('env', 'IPERF_SERVER_PORT') }}"
    webPort: "8080"
    webIP: "{{ lookup('env', 'IPERF_SERVER_WEBIP') }}"
  format: "{{ lookup('env', 'IPERF_FORMAT') }}"
  userfile: "/opt/{{ app.title }}/users.csv"
  protocol: "{{ lookup('env', 'IPERF_PROTOCOL') }}"
  username: "{{ lookup('env', 'IPERF_USERNAME') }}"
  password: "{{ lookup('env', 'IPERF_PASSWORD') }}"
web:
  port: "{{ lookup('env', 'WEB_PORT') }}"
pping:
  enable: "{{ lookup('env', 'PPING_ENABLE') }}"
  version: "{{ lookup('env', 'PPING_VERSION') }}"