run:
  user: www-data
  autoupdates: "{{ lookup('env', 'RUN_AUTOUPDATES') }}"
results:
  file:  "{{ lookup('env', 'RESULTS_FILE') }}"
  dir: "{{ lookup('env', 'RESULTS_DIR') }}"
app:
  title: "waddleperf"
build:
  threads: "{{ lookup('env', 'BUILD_THREADS') }}"
iperf:
  authentication: "{{ lookup('env', 'IPERF_AUTHENTICATION') }}"
  url: "{{ lookup('env', 'IPERF_URL') }}"
  client:
    enabled: "{{ lookup('env', 'IPERF_CLIENT_ENABLED') }}"
    streams: "{{ lookup('env', 'IPERF_CLIENT_STREAMS') }}"
    bitrate: "{{ lookup('env', 'IPERF_CLIENT_BITRATE') }}"
    return: "{{ lookup('env', 'IPERF_CLIENT_RETURN') }}"
    logfile: "{{ lookup('env', 'IPERF_CLIENT_LOGFILE') }}"
  server:
    enabled: "{{ lookup('env', 'IPERF_SERVER_ENABLE') }}"
    ip: "{{ lookup('env', 'IPERF_SERVER_IP') }}"
    port: "{{ lookup('env', 'IPERF_SERVER_PORT') }}"
  format: json
  userfile: "/opt/{{ app.title }}/users.csv"
  protocol: "{{ lookup('env', 'IPERF_PROTOCOL') }}"
  username: "{{ lookup('env', 'IPERF_USERNAME') }}"
  password: "{{ lookup('env', 'IPERF_PASSWORD') }}"
web:
  port: "{{ lookup('env', 'WEB_PORT') }}"
  sport: "{{ lookup('env', 'WEB_SPORT') }}"
  host: "{{ lookup('env', 'WEB_HOST') }}"
mtr:
  version: "{{ lookup('env', 'MTR_VERSION') }}"
  enabled: "{{ lookup('env', 'MTR_ENABLED') }}"
  compile: "{{ lookup('env', 'MTR_COMPILED') }}"
  max_hop: "{{ lookup('env', 'MTR_MAX_HOP') }}"
  use6: "{{ lookup('env', 'MTR_USE6') }}"
  use4: "{{ lookup('env', 'MTR_USE4') }}"
  localport: "{{ lookup('env', 'MTR_LOCALPORT') }}"
  destport: "{{ lookup('env', 'MTR_DESTPORT') }}"
  desthost: "{{ lookup('env', 'MTR_DESTHOST') }}"
  packet:
    size: "{{ lookup('env', 'MTR_PACKET_SIZE') }}"
    count: "{{ lookup('env', 'MTR_PACKET_COUNT') }}"
    interval: "{{ lookup('env', 'MTR_PACKET_INTERVAL') }}"
    protocol: "{{ lookup('env', 'MTR_PACKET_PROTOCOL') }}"  # icmp, udp, tcp
    tos: "{{ lookup('env', 'MTR_PACKET_TOS') }}"
    timeout: "{{ lookup('env', 'MTR_PACKET_TIMEOUT') }}"
  lookups:
    domains: "{{ lookup('env', 'MTR_LOOKUPS_DNS') }}"
    ipinfo: "{{ lookup('env', 'MTR_LOOKUPS_IPINFO') }}"
    asninfo: "{{ lookup('env', 'MTR_LOOKUPS_ASNINFO') }}"
pping:
  version: "{{ lookup('env', 'PPING_VERSION') }}"
  enabled: "{{ lookup('env', 'PPING_ENABLED') }}"
  protocol: "{{ lookup('env', 'PPING_PROTOCOL') }}"
  count: "{{ lookup('env', 'PPING_COUNT') }}"
  interval: "{{ lookup('env', 'PPING_INTERVAL') }}"
  use4: "{{ lookup('env', 'PPING_USE4') }}"
  use6: "{{ lookup('env', 'PPING_USE6') }}"
  destport: "{{ lookup('env', 'PPING_DESTPORT') }}"
  desthost: "{{ lookup('env', 'PPING_DESTHOST') }}"
httptrace:
  enabled: "{{ lookup('env', 'HTTPTRACE_ENABLED')  }}"
  url: "{{ lookup('env', 'HTTPTRACE_URL') }}"
s3:
  interval: "{{ lookup('env', 'S3_INTERVAL') }}"
  enabled: "{{ lookup('env', 'S3_ENABLED') }}"
  url: "{{ lookup('env', 'S3_URL') }}"
  bucket: "{{ lookup('env', 'S3_BUCKET') }}"
  encrypt: "{{ lookup('env', 'S3_ENCRYPT') }}"
  compatibility: "{{ lookup('env', 'S3_COMPATIBILITY') }}"
  key:
    access: "{{ lookup('env', 'S3_KEY_ACCESS') }}"
    secret: "{{ lookup('env', 'S3_KEY_SECRET') }}"
healthcheck:
  enabled: "{{ lookup('env', 'HEALTHCHECK_ENABLED') }}"
  interval: "{{ lookup('env', 'HEALTHCHECK_INTERVAL') }}"
autoperf:
  enabled: "{{ lookup('env', 'AUTOPERF_ENABLED') }}"
  interval: "{{ lookup('env', 'AUTOPERF_INTERVAL') }}"
sshping:
  enabled: "{{ lookup('env', 'SSHPING_ENABLED') }}"
  bandwidth_test: "{{ lookup('env', 'SSHPING_BANDWIDTH') }}"
  count: "{{ lookup('env', 'SSHPING_COUNT') }}"
  timeout: "{{ lookup('env', 'SSHPING_TIMEOUT') }}"
  target: "{{ lookup('env', 'SSHPING_DESTHOST') }}"
  user: "{{ lookup('env', 'SSHPING_USER') }}"
  port: "{{ lookup('env', 'SSHPING_PORT') }}"

