---
- name: Move client into local bin
  ansible.builtin.template:
    src: /opt/manager/templates/iperf3-client.j2
    dest: "/opt/{{ app.title }}/iperf3-client"
    mode: "0555"
- name: Get Server Public Key
  ansible.builtin.get_url:
    url: https://{{ iperf.server.webIP }}:{{ iperf.server.webPort }}/public.pem
    dest: "/var/www/{{ app.title }}/public.pem"
    backup: true
  when: iperf.server.enable == "0"
  ignore_errors: true
