---
- name: Move server into place
  ansible.builtin.template:
    src: /opt/manager/templates/iperf3-server.j2
    dest: "/opt/{{ app.title }}/iperf3-server"
    mode: "0555"
- name: Fill in start script if server enabled
  ansible.builtin.lineinfile:
    line: "nohup /opt/{{ app.title }}/iperf3-server"
    path: "/opt/manager/bins/server.sh"
    mode: "0555"
