---
- name: Move server into place
  ansible.builtin.template:
    src: /opt/manager/templates/iperf3-server.j2
    dest: "/opt/{{ app.title }}/iperf3-server"
    mode: "0555"
- name: Move pyweb into place
  ansible.builtin.template:
    src: /opt/manager/templates/pyweb.j2
    dest: "/opt/{{ app.title }}/pyweb.sh"
    mode: "0555"
- name: Fill in start script if server enabled
  ansible.builtin.lineinfile:
    line: "nohup /opt/{{ app.title }}/iperf3-server"
    path: "/opt/manager/bins/server.sh"
    mode: "0555"
- name: Setup hash generator
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/generate-hash.j2"
    dest: "/opt/manager/bins/hash.sh"
    mode: "0500"
# noqa
- name: Generate hash
  ansible.builtin.shell:
    cmd: /opt/manager/bins/hash.sh
  register: user_hash
  tags:
    - skip_ansible_lint
- name: User added
  debug:
    msg: "{{ iperf.username }},{{ user_hash.stdout }}"
- name: Generate userfile
  ansible.builtin.copy:
    content: "{{ iperf.username }},{{ user_hash.stdout }}\n"
    dest: "{{ iperf.userfile }}"
