---
- name: Run pping
  ansible.builtin.command:
    cmd: "bins/pping-parser.py -t http -a {{ httping.host}} -p {{ httping.port }} -j {{ results_dir }}/httping.json"
  when: pping.enabled
  tags: 
    - tier1

- name: Run mttr
  ansible.builtin.command:
    cmd: mttr-client
  when: mttr.enabled
  tags: 
    - tier1

- name: Run udpping
  ansible.builtin.command:
    cmd: udpping
  when: udpping.enabled
  tags: 
    - tier1

- name: Run sshping
  ansible.builtin.command:
    cmd: sshping
  when: sshping.enabled
  tags: 
    - tier2

- name: Run httptrace
  ansible.builtin.command:
    cmd: httptrace
  when: httptrace.enabled
  tags: 
    - tier2

- name: Run the iperf-client script
  ansible.builtin.command:
    cmd: iperf3-client
  when: iperf.enabled
  tags: 
    - tier3