---
- name: Move iperf3 client script into opt dir
  when: iperf.client.enabled
  ansible.builtin.template:
    src: /opt/manager/templates/iperf3-client.j2
    dest: "/opt/{{ app.title }}/iperf3-client"
    mode: "0555"
    owner: "{{ run.user }}"
    group: "{{ run.user }}"
- name: Get Server Public Key
  when: not iperf.server.enabled
  ansible.builtin.get_url:
    url: https://{{ web.host }}:{{ web.port }}/public.pem
    dest: "/var/www/{{ app.title }}/public.pem"
    backup: true
    owner: "{{ run.user }}"
    group: "{{ run.user }}"
    mode: "0500"
- name: Copy mtr client script into opt dir
  when: mtr.enabled
  ansible.builtin.template:
    src: /opt/manager/templates/mtr.j2
    dest: "/opt/{{ app.title }}/mtr-client"
    mode: "0555"
    owner: "{{ run.user }}"
    group: "{{ run.user }}"
- name: Copy pping client script into opt dir
  when: pping.enabled
  ansible.builtin.template:
    src: /opt/manager/templates/mtr.j2
    dest: "/opt/{{ app.title }}/pping-client"
    mode: "0555"
    owner: "{{ run.user }}"
    group: "{{ run.user }}"
- name: Copy http trace client script into opt dir
  when: httptrace.enabled
  ansible.builtin.template:
    src: /opt/manager/templates/mtr.j2
    dest: "/opt/{{ app.title }}/httptrace-client"
    mode: "0555"
    owner: "{{ run.user }}"
    group: "{{ run.user }}"
