---
- name: Copy pping to binary directory
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/pping.j2"
    dest:  "/opt/{{ app.title }}/pping-client"
    owner: "{{run.user}}"
    group: "{{run.user}}"
    mode: "0755"
