---
- name: Create sshping binary
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/sshping.j2"
    dest:  "/opt/{{ app.title }}/sshping-client"
    owner: "{{ run.user }}"
    group: "{{ run.user }}"
    mode: "0555"
